name: ML Model CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: us-west-1
  S3_BUCKET: s3://mlops-demo-s3-dvc-models
  MODEL_PATH: models/churn_model.pkl
  K8S_MANIFEST: k8s/inference.yaml

jobs:
  build-and-deploy:
    name: Build, Train, and Deploy Model
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push commits

    steps:
      - name: Configure Git
        run: git config --global core.longpaths true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure directories exist
        run: |
          mkdir -p models data
          pwd
          ls -la

      - name: Generate synthetic data
        run: python generate_data.py

      - name: Train model
        run: python train.py

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload model to S3
        run: |
          aws s3 cp ${{ env.MODEL_PATH }} ${{ env.S3_BUCKET }}/
          echo "Model pushed to S3 is success !!"

      - name: Update inference.yaml with S3 model path
        run: |
          MODEL_URI="s3://mlops-demo-s3-dvc-models/models/churn_model.pkl"
          sed -i "s|storageUri: .*|storageUri: $MODEL_URI|g" k8s/inference.yaml
          cat k8s/inference.yaml
    
      - name: Commit updated inference.yaml
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add k8s/inference.yaml
          git commit -m "Update model S3 path [skip ci]" || echo "No changes"
          git push || echo "No changes to push"

      